exports.statusCodes = {
  SUCCESS: 200,
  CREATED: 201,
  NO_CONTENT: 204,
  NOT_MODIFIED: 304,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  CONFLICT: 409,
  SERVER_ERR: 500,
};

exports.errorNames = {
  VALIDATION: "VALIDN_ERR",
  DB: "DB_ERR",
  SYSTEM: "SYSM_ERR",
  INVALID_REQUEST: "INVALREQ_ERR",
  UNAUTHORIZED: "UNAUTH_ERR",
};
